# server
server:
  port: 8080

# spring
spring:
  application:
    name: abcmsc-consumer-depart
  # cloud
  cloud:
    nacos:
      discovery:
        # server-addr: 127.0.0.1:8848
        server-addr: 127.0.0.1:8847,127.0.0.1:8848,127.0.0.1:8849