# server
server:
  port: 8081
# spring
spring:
  application:
    name: wyx-provider
  # cloud
  cloud:
    nacos:
      discovery:
        # server-addr: 127.0.0.1:8848
        server-addr: 127.0.0.1:8847,127.0.0.1:8848,127.0.0.1:8849
  # jpa
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  # datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wyx_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
# logging
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.abc: debug

